version: "3.3"

services:
  api:
    image: gchavesvds/simple-api-swarm
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    restart: unless-stopped
    ports:
      - 5000
    networks:
      - traefik-public
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-public-http.rule=Host(`simple-api.cluster.hiboux.me`)"
      - "traefik.http.routers.traefik-public-https.rule=Host(`simple-api.cluster.hiboux.me`)"
      - "traefik.http.routers.traefik-public-http.entrypoints=http"
      - "traefik.http.routers.traefik-public-http.entrypoints=https"
      - "traefik.http.routers.traefik-public-https.tls.certresolver=le"
    deploy:
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s

networks:
  traefik-public:
    external: true
  backend:
