version: "3"

services:
  api:
    image: gchavesvds/simple-api-swarm
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    restart: unless-stopped
    ports:
      - 5000
    networks:
      - net
      - backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=5000"
        - "traefik.frontend.rule='Host:simple-api.cluster.hiboux.me'"
      mode: replicated
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s

networks:
  net:
    external: true
  backend:
