version: "3.3"

services:
  api:
    image: gchavesvds/simple-api-swarm
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    restart: unless-stopped
    ports:
      - 5000
    networks:
      - traefik-public
      - backend
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.enable=true"
      - "traefik.http.routers.api_api.rule=Host(`simple-api.cluster.hiboux.me`)"
      - "traefik.http.services.api_api.loadbalancer.server.port=5000"
    deploy:
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s

networks:
  traefik-public:
    external: true
  backend:
