version: 3

services:
  api:
    image: gchavesvds/simple-api-swarm
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    restart: unless-stopped
    ports:
      - 5000
    networks:
      - traefik-public
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`simple-api.cluster.hiboux.me`)"
      - "traefik.http.routers.myapp.tls.certresolver=le"
      - "traefik.http.services.myapp.loadbalancer.server.port=80"
      - "traefik.http.services.myapp.loadbalancer.passhostheader=true"
      - "traefik.http.services.myapp.loadbalancer.healthcheck.path=/healthcheck"
      - "traefik.http.services.myapp.loadbalancer.healthcheck.interval=100ms"
      - "traefik.http.services.myapp.loadbalancer.healthcheck.timeout=75ms"
      - "traefik.http.services.myapp.loadbalancer.healthcheck.scheme=http"
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s

networks:
  traefik-public:
    external: true
  backend:
